### ISSUE TITLE
Index doesn't follow registered conventions

### ISSUE THREAD

**Issue by thorhj** [BVNetwork/InspectInIndex#1]
When pressing _Index_ or _Reindex_ from the index inspection page for a content item, the content is indexed without following the registered conventions for that type. 

**Example**

I have added the following convention:

```
_contentIndexer
    .Conventions
    .ForInstancesOf<IIndexable>()
    .ShouldIndex(indexable => !indexable.ExcludeFromIndex)
```

When I use the Index button on a page implementing the IIndexable interface and having `ExcludeFromIndex==true`, the content is indexed nonetheless and the convention is not evaluated.

This is a different behavior from the default Episerver content indexing (for instance when publishing a page).

**Comment by svenrog** [comment]
This might be fixed by merging #8.
