### ISSUE TITLE
.NET5 / Optimizely CMS 12-compatible version

### ISSUE THREAD

**Issue by LinusEkstrom** [BVNetwork/InspectInIndex#10]
With Optimizely CMS 12 publicly available since september 2021 I would like to know if there's any plans to upgrade this module to support the newest version?

**Comment by oyvindwh** [comment]
@haugsten

**Comment by haugsten** [comment]
@LinusEkstrom The module is upgraded to support CMS 12. See https://github.com/BVNetwork/InspectInIndex/tree/feature/netcore 

But we have not solved how to hide or show the plugin (show or hide "select view" option) yet.  HideFromViewMenu in the ViewConfiguration constructor is not working to hide or show the plugin for different users in CMS 12. We have created a support ticket but if you have any suggestions to solve this please let me know.

**Comment by LinusEkstrom** [comment]
Thanks for the status update @haugsten . Let's see if you can get support in the ticket soon - if you need help escalating this I could potentially help and then I need the ticket ID.

**Comment by LinusEkstrom** [comment]
Any updates on this @haugsten ?

**Comment by TheTh1rt33nth** [comment]
Good day to you, @haugsten ! 
Can I kindly inquire if the development of the project is still active, and shall we expect an Optimizely 12 - compatible version in any observable future?

**Comment by haugsten** [comment]
Optimizely 12 compatible version 2.0.0 released.

https://nuget.optimizely.com/package/?id=EPiCode.InspectInIndex
