### ISSUE TITLE
Issue with EPiServer version 11.5.4

### ISSUE THREAD

**Issue by ggroot** [BVNetwork/InspectInIndex#2]
Can you confirm this still works with EPiServer version 11.5.4.
Right when I try to access the page in the index it returns 'Content was not found in index.'

**Comment by eripe** [comment]
I got the same issue not working in later then 11.3.1 as it seems. I am getting this error in consle everytime we try to run reindex:

The store was queried with a [string] but the entity id is a [undefined]

Unable to load /admui/Find/proxy/XXX_StandardPage/_ce52be09-7c22-430a-86d3-89bf015cd05b_sv status: 404". 
But I can reindex the site. Also for pages with index I can view them but get information about it is index with episerver 11.3.1.

**Comment by eripe** [comment]
More information. Looks like it is find 13.0.1 that is the problem 12.7.1 is working.

This will result in a perfect json
http://localhost:35772/EPiServer/Find/proxy/Playground_Models_Pages_StartPage/_ae64f6c4-7b7e-48b7-b9c5-f46aaaa4c120_en 

{
"_index": "xxx_testindex",
"_type": "Playground_Models_Pages_StartPage",
"_id": "_ae64f6c4-7b7e-48b7-b9c5-f46aaaa4c120_en",
"exists": false
}

When upgrading to 13.0.1 you are unable to index and hence urls like above give you 404..

**Comment by paulieadam** [comment]
This bug has been reported to episerver.

You can upvote and follow the progress here:
[https://world.episerver.com/support/Bug-list/bug/FIND-3746](https://world.episerver.com/support/Bug-list/bug/FIND-3746)

**Comment by martinhenrysson** [comment]
There's a fix applied now. Any idea when a new version might appear in Episerver's NuGet feed?

**Comment by haugsten** [comment]
EPiCode.InspectInIndex.1.5.0.nupkg is now available on Episerver NuGet.
