### ISSUE TITLE
404 with Episerver Edit view

### ISSUE THREAD

**Issue by joemayberry** [BVNetwork/InspectInIndex#5]
Installed the InspectInIndex package to a fresh, up-to-date Alloy site (11.13.2.0), and seeing a 404 error when trying to use the Inspect In Index view.

![2019-12-03 12_03_04-DevTools - localhost_52471_EPiServer_Cms_](https://user-images.githubusercontent.com/47357457/70072470-0b447d80-15c5-11ea-9769-c50c22ae71d1.png)

**Comment by ggroot** [comment]
Try to install the nuget EPiServer.Packaging. This fixed it for me.

**Comment by joemayberry** [comment]
That resolved the issue. Thank you @ggroot
